# Generated by Django 4.1.9 on 2023-06-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_description_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='average_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3),
        ),
    ]
